### ISSUE TITLE
Need help using ArduinoOTA with Arduino Mega

### ISSUE THREAD

**Issue by SandraWeddig** [jandrassy/ArduinoOTA#10]
Hi!

I have an Arduino Mega 2560 and would like to do OTA updates of my sketches.
As I understand, this is possible with you project.
Is there a step by step tutorial how to use it?
How can I get network ports in my Arduino IDE?

Thanks,
Sandra

**Comment by jandrassy** [comment]
yes, it is possible
did you read this? https://github.com/jandrassy/ArduinoOTA#atmega-support

**Comment by SandraWeddig** [comment]
Yes, I did read it. But I'm not sure, if I did understand and follow it all.

I did copy my_boards to /opt/arduino/hardware.

Then I did burn the bootloader Arduino Mega 2560 (Optiboot) to my board.
After this I did burn the network configuration (I use an ethernet shield) to the board and uploaded my sketch in which I did add "#include <ArduinoOTA.h>", "ArduinoOTA.begin(Ethernet.localIP(), "Arduino", "password", InternalStorage);" at the end of the setup function and "ArduinoOTA.poll();" in the loop().

There appears no network port in my Arduin IDE. I have disabled my client firewall and can ping the board.

**Comment by jandrassy** [comment]
did you try the OTEthernet example?

**Comment by SandraWeddig** [comment]
Yes, and it didn't worked till I changed to ArduinoIDE 1.8.3.

The bug https://github.com/arduino/Arduino/issues/8408 blocks network ports since version 1.8.5.

Thanks for your help. I will try the OTA update next (board is already under network ports) and give you feedback.

**Comment by jandrassy** [comment]
but make sure you have AVR boards package at least version 1.6.21 installed for upload tool arduinoOTA version 1.2.

**Comment by SandraWeddig** [comment]
I still fail at the password... with the default. :(

**Comment by jandrassy** [comment]
copy here the upload command from the IDE console

**Comment by SandraWeddig** [comment]
I only see "Resetting the board
Failed to reset the board, upload failed" in the command line, when I press the upload button from Arduin IDE. Now it works with version 1.8.9 also, but I doesn't differ when asking for the password.

**Comment by jandrassy** [comment]
in Preferences check verbose mode for Upload

**Comment by SandraWeddig** [comment]
The command is "/root/.arduino15/packages/arduino/tools/arduinoOTA/1.3.0/bin/arduinoOTA -address 192.168.69.201 -port {upload.network.port} -sketch /tmp/arduino_build_393267/OTEthernet.ino.hex -upload {upload.network.endpoint_upload} -sync {upload.network.endpoint_sync} -reset {upload.network.endpoint_reset} -sync_exp {upload.network.sync_return} "

**Comment by jandrassy** [comment]
upload with my_boards Mega

**Comment by SandraWeddig** [comment]
I use the entry "Arduino Mega 2560 (Optiboot)".

**Comment by jandrassy** [comment]
then try to copy platform.local.txt from extras/avr folder, next to platform.txt in the AVR boards package Packages are located in ~/.arduino15/packages/ on Linux and %userprofile%\AppData\Local\Arduino15\packages\ on Windows (AppData is a hidden folder).

**Comment by SandraWeddig** [comment]
That did the trick :) 

Thanks, I can now upload via OTA.

**Comment by Kashyapkoshti** [comment]
> That did the trick :)
> 
> Thanks, I can now upload via OTA.

Can you please provide step by step procedure from beginning?
