### ISSUE TITLE
Problem with OTA upload - Mega1284p (mightycore)

### ISSUE THREAD

**Issue by muellerjm** [jandrassy/ArduinoOTA#102]
I have problems with an Atmega 1284p and Migthyocore....

In Arduino IDE (Windows) Ota upload is not possible. i get the error message:
avrdude: ser_open(): can't open device "10.1.1.122".

But with an Arduino MKR Zero it works without problems.

What am I doing wrong?

Thanks a lot

**Comment by jandrassy** [comment]
copy platform.local.txt from library's extras/avr folder, next to platform.txt in MightyCore

**Comment by muellerjm** [comment]
thank you... everything good
