### ISSUE TITLE
Callback functions

### ISSUE THREAD

**Issue by aryadas98** [jandrassy/ArduinoOTA#135]
The ESP ArduinoOTA library has some callback functions like `onStart()`, `onEnd()`, `onProgress()`, `onError()`.  I wanted to know whether there are any such callback functions in this library. Would be useful in debugging issues.

Thank you for writing this excellent library. 🎉

**Comment by jandrassy** [comment]
https://github.com/jandrassy/ArduinoOTA/blob/master/src/WiFiOTA.h#L45-L52
