### ISSUE TITLE
Error while OTA uploading

### ISSUE THREAD

**Issue by pscott-ams** [jandrassy/ArduinoOTA#143]
I'm trying the OTEthernet example in Arduino IDE. I'm using a WeMos D1 Mini32 wired to a W5500 via SPI.

The example is able to upload normally, but when I try to upload using programmer, I get this message:

```
Sketch uses 262833 bytes (20%) of program storage space. Maximum is 1310720 bytes.
Global variables use 17000 bytes (5%) of dynamic memory, leaving 310680 bytes for local variables. Maximum is 327680 bytes.
Error while uploading: missing 'program.params.quiet' configuration parameter
```

I used the "fake programmer" method described in the README.

**Comment by jandrassy** [comment]
the 'fake programmer' doesn't use program.params.quiet

**Comment by pscott-ams** [comment]
Yes, and I'm not sure why the program is looking for program.params.quiet

This is what my programmers.txt looks like:

```
arduinoOTA104.name=Arduino OTA (192.168.167.101)
arduinoOTA104.program.tool=arduinoOTA
arduinoOTA104.ip=192.168.167.101
```

And this is the folder where the platform.txt and programmers.txt are:

![image](https://user-images.githubusercontent.com/91959309/159046313-d1d991c5-e1fd-4871-92c3-48a3b0ffff1c.png)

Does it look like I did something wrong when adding the platform.local.txt?
Is my programmers.txt file wrong?

**Comment by pscott-ams** [comment]
Yes, and I'm not sure why the program is looking for program.params.quiet

This is what my programmers.txt looks like:

```
arduinoOTA104.name=Arduino OTA (192.168.167.101)
arduinoOTA104.program.tool=arduinoOTA
arduinoOTA104.ip=192.168.167.101
```

And this is the folder where the platform.txt and programmers.txt are:

![image](https://user-images.githubusercontent.com/91959309/159046313-d1d991c5-e1fd-4871-92c3-48a3b0ffff1c.png)

Does it look like I did something wrong when adding the platform.local.txt?
Is my programmers.txt file wrong?

**Comment by pscott-ams** [comment]
I got maxgerhardt's example to work on PlatformIO
