### ISSUE TITLE
OTASketchDownload partitions

### ISSUE THREAD

**Issue by Bluebird-Software** [jandrassy/ArduinoOTA#144]
I use the OTASketchDownload.ino example to update via a HTTP server. The file is being downloaded successfully and the update works. 

I have the next partitions:

- nvs
- otadata
- app0
- app1
- spiffs

Is the update being downloaded to the otadata partition? How does this libary work

**Comment by jandrassy** [comment]
the esp32 Update library is used to store and apply the update binary

**Comment by Bluebird-Software** [comment]
So how would you suggest the partitions. Do i need otadata and app0 and app1? or just 1 big app0 partition?

**Comment by jandrassy** [comment]
see the esp32 Update library

**Comment by Bluebird-Software** [comment]
A little help would be appreciated. 
You mean this? https://github.com/espressif/arduino-esp32/tree/master/libraries/Update

How do i get the answer to my question?

**Comment by jandrassy** [comment]
I don't know anything about esp32 partitions
