### ISSUE TITLE
Nano IOT 33 - WifiOTA Sketch Download

### ISSUE THREAD

**Issue by JEG8** [jandrassy/ArduinoOTA#145]
Hello,

I am using OTA sketch download using the example code provided (OTASketchDownloadWifi). 

The example sketch uses 38724 bytes (14%) of program storage space. I am trying to download a sketch that uses 148164 bytes (56%) of program storage space. Maximum storage on my device is 262144 bytes. I am receiving the following error.

**Update status code: 200
Server returned update file of size 147676 bytes
There is not enough space to store the update. Can't continue with update.**

Is there any way that I can make this work besides reducing the size of my update? 

Thanks for any help you can provide and thank you for this library.

**Comment by jandrassy** [comment]
you can use SD card to store the update binary (or to store the data which are now in the sketch and make it big)

**Comment by JEG8** [comment]
Thank you. I had the same thought but when I try to use OTASketchDownload_SD for the Arduino Nano 33 IOT, it says the board is unsupported. I think this is due to the SDU library not supporting the board.

**\Arduino15\packages\arduino\hardware\samd\1.8.13\libraries\SDU\src\SDU.cpp:44:4: error: #error "Unsupported board!"
   #error "Unsupported board!"
    ^~~~~**

What do you recommend I use for storing the binary to the SD?

**Comment by jandrassy** [comment]
https://github.com/arduino/ArduinoCore-samd/pull/645
