### ISSUE TITLE
Arduino Mega 2560 OTA problem

### ISSUE THREAD

**Issue by alberts112** [JAndrassy/ArduinoOTA#153]
Hello,

I manage to use Arduino OTA but after Sketch uploaded successfully message the board start running the initial sketch. Upload message is succes but happens no change to board sketch. What can i check ? 

Thank you

**Comment by JAndrassy** [comment]
https://github.com/JAndrassy/ArduinoOTA#upload-returns-ok-but-the-sketch-is-not-replaced
