### ISSUE TITLE
BLE Support

### ISSUE THREAD

**Issue by vovagorodok** [JAndrassy/ArduinoOTA#156]
Any plans to add support OTA over BLE?
Found this one: https://github.com/fbiego/ESP32_BLE_OTA_Arduino
Will be nice to have here such functionality

**Comment by JAndrassy** [comment]
> Any plans to add support OTA over BLE? Found this one: https://github.com/fbiego/ESP32_BLE_OTA_Arduino Will be nice to have here such functionality

just use InternalStorage object from this library instead of the esp32 Update object
