### ISSUE TITLE
Add support for STM32F4xx

### ISSUE THREAD

**Issue by wowtah** [JAndrassy/ArduinoOTA#158]
First of all, awesome job on adding STM32 support to the library. Greatly appreciated, since I can't find any STM32 OTA libraries  that support wired ethernet. 

Secondly, my request, since I am using a STM32F411 instead of a STM32F103: 

Would it be possible to add **STM32F4** support also? I have tried to adapt the code to STM32F4 but I get some errors (mostly from stm32_flash_boot.c) that are above my knowledge level of the differences in memory structure between STM32F1 and F4 (PAGES vs SECTORS, etc).

**Comment by JAndrassy** [comment]
I don't have the hardware. Once I had hope that the STM32 Arduino team would add STM32 support to ArduinoOTA library.

**Comment by JAndrassy** [comment]
coffee inspires :-) I order a Black Pill. anyway it is the next most used STM32 Arduino

**Comment by wowtah** [comment]
> coffee inspires :-) I order a Black Pill. anyway it is the next most used STM32 Arduino

Awesome :D

**Comment by JAndrassy** [comment]
I started working on it today.

**Comment by JAndrassy** [comment]
it's working.
now I have to consolidate the code. test again. then retest with the BluePill because of shared code.

**Comment by JAndrassy** [comment]
you can try it

**Comment by wowtah** [comment]
Awesome. I will check it out!

**Comment by wowtah** [comment]
Works like a charm. Thanks so much!
