### ISSUE TITLE
Arduino IDE 2.0 Error with fake progrmmer method

### ISSUE THREAD

**Issue by AcThPaU** [JAndrassy/ArduinoOTA#161]
`Property 'program.tool.' is undefined`

`tools.arduinoOTA.cmd={runtime.tools.arduinoOTA.path}/bin/arduinoOTA
tools.arduinoOTA.program.params.verbose=
tools.arduinoOTA.program.params.quiet=
tools.arduinoOTA.program.pattern="{cmd}" -address {ip} -port 65280 -username arduino -password password -sketch "{build.path}/{build.project_name}.bin" -upload /sketch -b`

`arduinoOTA104.name=Arduino OTA
arduinoOTA104.program.tool = arduinoOTA
arduinoOTA104.ip=192.168.1.236`

**Comment by JAndrassy** [comment]
try the GitHub version. there is a fix but I didn't create a release yet

**Comment by AcThPaU** [comment]
tried, still the same error

**Comment by AcThPaU** [comment]
you did not update samd for 3 years.

**Comment by JAndrassy** [comment]
sorry but how should I know you use SAMD? AVR is updated. but not the fake programmer I see now. I think programmers didn't work in IDE 2 when I added support for it in avc/platform.local.txt

**Comment by JAndrassy** [comment]
it is a bug in IDE 2. upload with fake programmer works for custom boards definitions in hardware folder (my_boards), but it ends with error "Property 'program.tool.serial' is undefined" for boards from installed packages. `program.tool.serial` is not used by fake programmer.

**Comment by JAndrassy** [comment]
https://github.com/arduino/arduino-ide/issues/1135

**Comment by JAndrassy** [comment]
so the solution is to add
```
arduinoOTA104.program.default=arduinoOTA
```
to definition in programmers.txt for IDE 2 and CLI
