### ISSUE TITLE
ESP32 OTEthernet compilation error.

### ISSUE THREAD

**Issue by Arda-Bildik** [JAndrassy/ArduinoOTA#168]
Hi,

I'm currently working on a project with esp32 and I wanted to add OTA functionality with W5100.
I got the error "Compilation error for ESP32 Dev Module" while trying to upload the OTEthernet example.
This is the output from Arduino IDE:
![image](https://user-images.githubusercontent.com/63192624/188964541-4d8c8d2f-61ca-443d-b3b8-d4ac2da57f25.png)
I had a look in the code and tried including InternalStorage.h in the example code and 2 extra errors added to previous errors:
![image](https://user-images.githubusercontent.com/63192624/188965251-96616644-5bda-44e8-8afc-779349efb754.png)
Also yes I did remove the ArduinoOTA library included with esp32 board package.

**Comment by JAndrassy** [comment]
it is this problem
https://github.com/arduino-libraries/Ethernet/issues/193

**Comment by Arda-Bildik** [comment]
> it is this problem [arduino-libraries/Ethernet#193](https://github.com/arduino-libraries/Ethernet/issues/193)

It seems like it I will try it. I'll post the fix if I find.

**Comment by JAndrassy** [comment]
> > it is this problem [arduino-libraries/Ethernet#193](https://github.com/arduino-libraries/Ethernet/issues/193)
> 
> It seems like it I will try it. I'll post the fix if I find.

there is my comment
