### ISSUE TITLE
Lack of complete guidance for programming.

### ISSUE THREAD

**Issue by amirhaaa** [JAndrassy/ArduinoOTA#172]
Dear JAndrassy

Hi
First of all, thank you for all the hard work you have done for this project, but I am still confused and cannot use your codes. I have a nodemcu board and I want to program my arduino uno through node mcu. What pins should I connect from nodemcu board to arduino uno board? Also, how can I load the binary code into the arduino uno via the web interface? I would be grateful if you could give me a complete guide with a complete picture or text, because it is a vital issue and if I don't use this project, I will lose my life.
Thank you for your attention.

gmail : aaabbbmir@gmail.com

**Comment by JAndrassy** [comment]
this library doesn't work for Uno
