### ISSUE TITLE
what if i reset?

### ISSUE THREAD

**Issue by KJPOUNDY132** [JAndrassy/ArduinoOTA#175]
what if i rest after update (https://github.com/JAndrassy/ArduinoOTA/blob/master/examples/OTEthernet/OTEthernet.ino)
keep updated firmware or download one more time on every update

**Comment by JAndrassy** [comment]
the library resets the MCU after applying the update. do you have some issue?

**Comment by KJPOUNDY132** [comment]
i mean if i dont call update function on start up. it runs nothing or use last updated  firmware?

**Comment by JAndrassy** [comment]
there are never two sketches at once. an Arduino sketch is build for exact addresses in flash. it can only run if it is at required address in flash

**Comment by KJPOUNDY132** [comment]
i try to make ota trigger with mqtt.
if message equals OTA_OK esp32 gets new firmware.
but  the message is not equal OTA_OK use old firmware. is it posible?

**Comment by JAndrassy** [comment]
why do you use this library for esp32?

**Comment by KJPOUNDY132** [comment]
I haven't started trying because my Ethernet module hasn't arrived yet.
i just want to know;
Does the device download the file from the beginning every time it runs, or does it run the last file it received unless there is a new file?

**Comment by JAndrassy** [comment]
it is your running sketch which downloads and applies the new version. it is on you how your sketch determines if there is a new version to download

**Comment by KJPOUNDY132** [comment]
thank you
