### ISSUE TITLE
The connection is unstable？

### ISSUE THREAD

**Issue by sssSake** [JAndrassy/ArduinoOTA#176]
I use the arduino Mkr WiFi 1010, set up and start the OTA function, separate the arduino from the computer, and when connected to the power supply, the remote port is often not searched。
  It should be said that sometimes it can be searched, sometimes it is not.
  Why this is the case?

**Comment by JAndrassy** [comment]
the propagation of the OTA port uses mDNS and it has problems in some networks or with some computers and the implementation in ArduionOTA is not really robust either (it is inherited from Arduino's WiFi101OTA library).
I recommend
https://github.com/JAndrassy/ArduinoOTA#ota-upload-from-ide-without-network-port

**Comment by sssSake** [comment]
OK，I will try.

**Comment by sssSake** [comment]
Thank you for your reply.




李雷
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JAndrassy/ArduinoOTA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月9日(星期三) 下午2:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JAndrassy/ArduinoOTA] The connection is unstable？ (Issue #176)





 
the propagation of the OTA port uses mDNS and it has problems in some networks or with some computers and the implementation in ArduionOTA is not really robust either (it is inherited from Arduino's WiFi101OTA library).
 I recommend
 https://github.com/JAndrassy/ArduinoOTA#ota-upload-from-ide-without-network-port
