### ISSUE TITLE
ide stuck uploading

### ISSUE THREAD

**Issue by JurkoDev** [JAndrassy/ArduinoOTA#177]
am using the latest arduino ide and when i do an ota with a arduino mkr wifi 1010 it does upload and the code runs but the editor gets stuck and i cant upload if i dont reopen it 
![image](https://user-images.githubusercontent.com/50539591/204642115-a487cbc1-e862-4103-80fc-15666566cbf3.png)
i uploaded the wifinina ap web server example with the ota added (lib inclusion ota begin and ota pool in loop)

**Comment by JAndrassy** [comment]
the library did the job. it has no control of the upload tool and the IDE
