### ISSUE TITLE
Upload Error - ESP32 & W5500

### ISSUE THREAD

**Issue by jhnwmr** [JAndrassy/ArduinoOTA#186]
Hello,
I am using an ESP32 with W5500 Ethernet module.
I would like to have an easy way to update the ESP32 firmware. In the past it worked very well with the Ethernet.h and ArduinoOTA.h library.
After updating my Mac to macOS 13, I am unable to upload the sketch to the ESP32.
I get the following error message after the sketch is compiled correctly:

```
fatal error: runtime: bsdthread_register error
runtime stack:
runtime.throw(0x13693d0, 0x21)
/ssd/go/src/runtime/panic.go:616 +0x81 fp=0x7ff7bfeff608 sp=0x7ff7bfeff5e8 pc=0x1028be1
runtime.goenvs()
/ssd/go/src/runtime/os_darwin.go:129 +0x83 fp=0x7ff7bfeff638 sp=0x7ff7bfeff608 pc=0x1026763
runtime.schedinit()
/ssd/go/src/runtime/proc.go:501 +0xd6 fp=0x7ff7bfeff6a0 sp=0x7ff7bfeff638 pc=0x102b4d6
runtime.rt0_go(0x7ff7bfeff6d0, 0xe, 0x7ff7bfeff6d0, 0x1000000, 0xe, 0x7ff7bfeff8c8, 0x7ff7bfeff91f, 0x7ff7bfeff928, 0x7ff7bfeff938, 0x7ff7bfeff93e, ...)
/ssd/go/src/runtime/asm_amd64.s:252 +0x1f4 fp=0x7ff7bfeff6a8 sp=0x7ff7bfeff6a0 pc=0x1050fe4
Failed uploading: uploading error: exit status 2
```

Is there any solution to this problem?

**Comment by JAndrassy** [comment]
https://forum.arduino.cc/t/bsdthread-register-error-when-try-to-use-adruinoota-update/1090730
