### ISSUE TITLE
call function before flash

### ISSUE THREAD

**Issue by hedva92** [JAndrassy/ArduinoOTA#187]
Would it be possible to implement a method that would call some predefined function before flashing the firmware? Something like save variable values ​​to external memory (or etc), when this function ended, the firmware would be flashed. Ty

**Comment by JAndrassy** [comment]
it is not in the examples, but there is onStart and beforeApply
```
 ArduinoOTA.onStart([]() {watchdogStop();});
 ArduinoOTA.beforeApply(shutdown);
```
```
void shutdown() {
  eventsSave();
  statsSave();
}
```
