### ISSUE TITLE
After update only espota tool

### ISSUE THREAD

**Issue by jhnwmr** [JAndrassy/ArduinoOTA#198]
Hello,
I have updated the ESP32 core from 1.6.0 to 2.0.7 and IDE itself to 2.0.3. Now I can not upload OTA updates.
I replaced the original ArduinoOTA library with this one and added the platform.local.txt.
Compiling works fine, but uploading does not. It always uses the espota tool. 
However, the ArduinoOTA tool should be used.
What do I have to change so that the flashing works correctly?
Thanks!

**Comment by JAndrassy** [comment]
try this platform.local.txt for IDE 2
[platform.local.txt](https://github.com/JAndrassy/ArduinoOTA/files/11242496/platform.local.txt)

**Comment by lcoffin** [comment]
Cool. I’ll give that a try when I’m able to. I’m traveling for the week, so won’t be until I’m back.-LOn Apr 16, 2023, at 10:28 AM, Juraj Andrássy ***@***.***> wrote:﻿
try this platform.local.txt for IDE 2
platform.local.txt
