### ISSUE TITLE
OTA Program with SD Card crashing at 60% of program space used

### ISSUE THREAD

**Issue by egjohnson17** [jandrassy/ArduinoOTA#20]
Hello, 
Without the SD card and the ArduinoOTA library, my Arduino MKR1010 would crash at about 40% of program space used. However, now with the SD card the program crashes at about 61% of the available flash used. When I program via the Aruino IDE, it still says that the maximum program memory space is 262144 bytes even though I have connected the micro SD card. If the program binary is stored on the SD card why is my program crashing?
I don't think I am using very much RAM. This is for a FASTLED application and I am using the IoT MQTT communication capability of the Arduino MKR101. Each FASTLED pixel should use 3 bytes of SRAM and the Arduino MKR1010 should have 32kB of SRAM. I am storing some strings for print statements and I am doing networking and I have some animation functions. 
Thank you

**Comment by jandrassy** [comment]
upload fails? 
can you copy the verbose output of the upload from the IDE console? 

the SD card doesn't count as internal flash. the program can't run from SD card.
the SD is only used to temporary store the uploaded binary until reset. the SDU bootloads it then at next start.

the available SRAM isn't a problem. OTA uses only a 64 bytes buffer.
