### ISSUE TITLE
missing file Update.h on ESP32 

### ISSUE THREAD

**Issue by sdetweil** [JAndrassy/ArduinoOTA#202]
I am trying to incorporate vovagorodok/ArduinoBleOta in my project which depends on yours

but I get 
/ArduinoOTA/src/InternalStorageESP.cpp:24:10: fatal error: Update.h: No such file or directory build in platformio
```
#ifdef ESP32
#include <Update.h>
#endif
```

my project def is 
```

[env:esp32doit-devkit-v1-ota]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_flags = -D USE_ESP32_BLE_LIB -D ESP32
lib_deps = 
	arduino-libraries/Arduino_JSON@^0.2.0
	adafruit/Adafruit VL53L1X@^3.1.0
	https://github.com/vovagorodok/ArduinoBleOta
	jandrassy/ArduinoOTA@^1.0.9
	bakercp/CRC32@^2.0.0
	rlogiacco/CircularBuffer@^1.3.3
```
I had to use not internalStorage to build on ESP32 (I only needed eeprom access)

**Comment by JAndrassy** [comment]
"Update" is a library bundled with esp32 platform. and InternalStorage just wraps it. so you can use it directly instead of InternalStorage
