### ISSUE TITLE
Upload returns OK but the sketch is not replaced STM32 Nucleo

### ISSUE THREAD

**Issue by Yaroki2** [JAndrassy/ArduinoOTA#203]
Hello!
I do OTA use NUCLEO-F303RE and get
![image](https://user-images.githubusercontent.com/94787446/236831706-a2e0d494-67a8-4eb8-9f24-80b39e9367f2.png)
Then  MCU don't resets and stuck forever
i tried closing the Serial Monitor in the IDE but it doesn't work.
Can you help me, please?

**Comment by JAndrassy** [comment]
sorry, I don't have an STM32 F3 so it was never tested. The F3 has the same flash operations as F1 and I tested F1 so there was a chance it could work.

**Comment by Yaroki2** [comment]
Thanks you for the reply!
I realize I need to press the manual reset button to get it to work, do you have any ideas?

**Comment by JAndrassy** [comment]
is the sketch updated?

**Comment by Yaroki2** [comment]
Yes, Sketch updated but doesn't reset automatically

**Comment by JAndrassy** [comment]
InternalStorage.apply() calls at the end `NVIC_SystemReset();` which is a reset command for all ARM MCU and works on STM32 too.
you could test it in a simple sketch.

**Comment by Yaroki2** [comment]
I tested `NVIC_SystemReset();` with simple sketch and it works fine.
I think `NVIC_SystemReset();` is the reason, when i change other way to reset in library it works successfully.
