### ISSUE TITLE
Arduino Opta support

### ISSUE THREAD

**Issue by rickmoonex** [JAndrassy/ArduinoOTA#213]
Is the Arduino Opta (RS485) supported? If I'm not mistaken it runs on the STM32 platform which is supported.

When I try to use the example sketch it gives the error: `undefined reference to 'InternalStorage'`

My sketch looks as follows:

```cpp
#include <Ethernet.h>
#include <ArduinoOTA.h>
#include <SPI.h>

byte mac[] = {0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED};

void setup() {
    Serial.begin(9600);
    while (!Serial);

    Serial.println("Initialize Ethernet with DHCP:");
    if (Ethernet.begin(mac) == 0) {
        Serial.println("Failed to configure Ethernet using DHCP");
    } else {
        Serial.print("  DHCP assigned IP: ");
        Serial.println(Ethernet.localIP());
    }

    ArduinoOTA.begin(Ethernet.localIP(), "Arduino", "password", InternalStorage);
}

void loop() {
    ArduinoOTA.poll();
}
```

Thanks for any help, appreciate it!

**Comment by JAndrassy** [comment]
the STM32 boards are supported only with the STM32 Arduino core.
Arduino 'mbed' core is not supported for any board.
