### ISSUE TITLE
Error compiling for board Arduino Mega 2560 (Optiboot).

### ISSUE THREAD

**Issue by youssiefkhaled** [JAndrassy/ArduinoOTA#220]
` file included from C:\Users\Yousif\Documents\Arduino\libraries\WiFiNINA\src/WiFiStorage.h:23:0,
                 from C:\Users\Yousif\Documents\Arduino\libraries\WiFiNINA\src/WiFi.h:37,
                 from C:\Users\Yousif\Documents\Arduino\libraries\WiFiNINA\src/WiFiNINA.h:23,
                 from C:\Users\Yousif\Documents\Arduino\libraries\ArduinoOTA-master\examples\Advanced\OTASketchDownloadWifi\OTASketchDownloadWifi.ino:24:
C:\Users\Yousif\Documents\Arduino\libraries\WiFiNINA\src/utility/wifi_drv.h:293:12: error: 'PinStatus' does not name a type
     static PinStatus digitalRead(uint8_t pin);
`
i can't compile the arduinoOTA sketches ? 
for both 
WIFI101_OTA
OTAsketchDownloadWifi 
i also tested serialWIFIOTA it detects the esp but i dont know how to make it connect to the wifi network 
any help?

**Comment by youssiefkhaled** [comment]
> 

ok the solution was simply to replace the wifininawith wifiespat lib

**Comment by JAndrassy** [comment]
https://github.com/JAndrassy/WiFiEspAT#persistent-wifi-connection

**Comment by youssiefkhaled** [comment]
just a qustion 
i should now ulpoad this SetupWiFiConnection in the esp-01 and join my network 
after that what i should expect ?
a network port ?
or i will have to use the fake programmer?
 @JAndrassy

**Comment by youssiefkhaled** [comment]
i think i got it know i will come after testing

**Comment by youssiefkhaled** [comment]
ok what i did is reuploaded the serial ota with network connected 
and 
![Screenshot 2023-09-09 165048](https://github.com/JAndrassy/ArduinoOTA/assets/117771525/fcfb2579-f611-4c53-a09c-a7a8f348b985)
uncommented to get the static ip 
now there is no network port nor and i cant upload throw the "fake programmer"
i also edited the fake programer to static ip but i get this 

'connecting to board ... failed!
Error flashing the sketch
Error flashing the sketch
'

**Comment by youssiefkhaled** [comment]
i just had to move the platform.local
thank youuuuuuuuuuu
