### ISSUE TITLE
Password wrong

### ISSUE THREAD

**Issue by LukeScrewdriver** [JAndrassy/ArduinoOTA#221]
Hi, I'm trying to upload code to an arduino mega and an arduino nano 33 iot.

**Attempting on ide 2.x (for 33 Nano iot):**
When I try to upload the code it does not ask me for the password
I enabled the detailed output and noticed that it uses 'arduino' as the password.
I tried to run the program it points me to from the console with the correct parameters and it loaded correctly.

**Attempted on ide 1.x (Arduino Mega):**
When I try to load the code it asks me for the password
I enter the password (which I verified) and then it asks for it over and over again as if it were wrong.
I enabled the detailed output and noticed that parameter are incorrect.

``` 
/home/luke/.arduino15/packages/arduino/tools/arduinoOTA/1.3.0/bin/arduinoOTA" -address 192.168.1.82 -port {upload.port.properties.port} -sketch "/tmp/arduino/sketches/F86C5CF794A753D560813E2D582387CA/ArduinoFirstFloor.ino.hex" -upload {upload.port.properties.endpoint_upload} -sync {upload.port.properties.endpoint_sync} -reset {upload.port.properties.endpoint_reset} -sync_exp {upload.port.properties.sync_return}
```

**Comment by JAndrassy** [comment]
password is the third parameter in ` ArduinoOTA.begin(WiFi.localIP(), "Arduino", "password", InternalStorage);`

for Mega you didn't copy platform.local.txt from extras to the boards package. it now uses the upload command for ArduinoYun.
https://github.com/JAndrassy/ArduinoOTA#atmega-support

**Comment by LukeScrewdriver** [comment]
I remembered installing them... now they are installed 
![immagine](https://github.com/JAndrassy/ArduinoOTA/assets/68291618/caeb50cf-42af-4885-b3dd-923172060ab6)



> password is the third parameter in  ArduinoOTA.begin(WiFi.localIP(), "Arduino", "password", InternalStorage);

Yes i changed the name and the password field


> do you have the latest version of the SAMD boards package?

Yes

**Comment by JAndrassy** [comment]
so now the upload command for Mega is OK?

**Comment by LukeScrewdriver** [comment]
Yes the upload to the mega has settled down.
I have another small problem but I will create another issue for that.
Thank you for responding to me quickly
