### ISSUE TITLE
WIFI101_OTA example 

### ISSUE THREAD

**Issue by mmanco89** [JAndrassy/ArduinoOTA#225]
prolly there is a mis-include in [WIFI101_OTA.ino](https://github.com/JAndrassy/ArduinoOTA/blob/5f838871e213474e7dabf70f2ddfc5ecb6cb971a/examples/WiFi101_OTA/WiFi101_OTA.ino#L22) example

`#include <WiFi101.h>` instead of `#include <WiFiNINA.h>`

**Comment by JAndrassy** [comment]
include the WiFi library of your choice. more people use WiFiNINA than WiFi101
