### ISSUE TITLE
"Connecting to board...done" but getting "Error flashing the sketch:Not Found" using SerialWifiOTA (Arduino Mega & ESP32)

### ISSUE THREAD

**Issue by mluthfialhadi** [JAndrassy/ArduinoOTA#227]
Hello, i am trying to upload SerialWifiOTA with ESP32 attached to Serial1 of Arduino Mega. As you mentioned in the readme, device using WifiEspAT cannot show under "port" name. So i used "fake programmer". But i always getting _"error flashing the sketch:not found"_. I have uploaded SerialWifiOTA manually using usb to arduino mega, then when I tried to upload using programmer, it only showed error not found.
I have flash optiboot into the mega board from your _"my_board"_ and flash AT firmware 2.4.0 into ESP32-wroom board.

Arduino Mega and ESP32 Connection to get AT command working is from ESP AT docs :
![image](https://github.com/JAndrassy/ArduinoOTA/assets/59685778/71ea7e8b-f176-4b9d-8067-6e0b1ade0097)

Here the error code from Arduino IDE 1.8.19:

```
Arduino: 1.8.19 (Windows 10), Board: "Arduino Mega 2560 (Optiboot)"
Sketch uses 16494 bytes (6%) of program storage space. Maximum is 261120 bytes.
Global variables use 1197 bytes (14%) of dynamic memory, leaving 6995 bytes for local variables. Maximum is 8192 bytes.

C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/arduinoOTA -address 192.168.1.65 -port 65280 -username Arduino -password password -sketch C:\Users\ACER\AppData\Local\Temp\arduino_build_787056/SerialWiFiOTA.ino.bin -upload /sketch -b 

Connecting to board ...  done
Uploading sketch ...  done
Flashing sketch ...  done
Error flashing the sketch:Not Found
Error flashing the sketch:Not Found

```

Sorry for my bad English, English is my third language.

**Comment by JAndrassy** [comment]
It looks like you have some older version of the upload tool in the IDE. Try to install the Arduino SAMD package. It will install a newer version.
