### ISSUE TITLE
Compilation error due ESP core changed

### ISSUE THREAD

**Issue by anklimov** [jandrassy/ArduinoOTA#23]
.platformio/lib/ArduinoOTA_ID6178/src/InternalStorageESP.cpp: In member function 'virtual int InternalStorageESPClass::open(int, uint8_t)':
/.platformio/lib/ArduinoOTA_ID6178/src/InternalStorageESP.cpp:35:56: error: 'U_SPIFFS' was not declared in this scope
   return Update.begin(length, command == 0 ? U_FLASH : U_SPIFFS);

The problem caused by dummy renaming in ESP core release:
                                         
https://github.com/esp8266/Arduino/commit/a389a995fb12459819e33970ec80695f1eaecc58

Suggested solution:

#ifndef U_SPIFFS
#define U_SPIFFS U_FS
#endif

**Comment by jandrassy** [comment]
solved with https://github.com/jandrassy/ArduinoOTA/pull/24
thank you
