### ISSUE TITLE
SDStorage open issue on Uno R4

### ISSUE THREAD

**Issue by n1coh** [JAndrassy/ArduinoOTA#233]
Hello,
I tried the OTA update via InternalStorage and it works fine.
I need the OTA update via SDStorage for space reasons.
So I tried the WiFi101_SD_OTA example but I still get the error: 
`Failed uploading: uploading error: exit status 1`

I've added some debugging in sendHttpResponse:
`Serial.print("OTA upload response: ");
  Serial.println(status);`

I went up to the to pollServer function and the error come from:
`!_storage->open(contentLength, dataUpload)`

My knowledge stops here, do you have any idea why writing doesn't work?

The SD exemples sketch work well btw

**Comment by JAndrassy** [comment]
the status is printed in IDE console with verbose mode set in Preferences.
what was the status?

**Comment by n1coh** [comment]
Fast response thank you
In my console:
`Connecting to board ...  done
Uploading sketch ...  done
Flashing sketch ... Error flashing the sketch
Failed uploading: uploading error: exit status 1`

**Comment by n1coh** [comment]
Other informations : I'm on Arduino IDE v2, when I use internal storage logs in console show `Failed uploading: uploading error: exit status 1` but with previous debug `OTA upload response: OK` and update is applied.
May my arduino IDE conf is wrong.

**Comment by JAndrassy** [comment]
could it be timeout of the upload tool? it is only 10 seconds.
newer version of the arduinoOTA tool allows a timeout parameter

**Comment by n1coh** [comment]
I think you are right, sometimes there is no error with InternalStorage.
I'm on version 1.3.0, is there a newer version?

**Comment by JAndrassy** [comment]
https://github.com/arduino/arduinoOTA/releases

replace the 1.3.0 exe and in platform.local.txt add the -t option in seconds

**Comment by n1coh** [comment]
Binary was hard to find but now everything is ok

Thank you for your time and work

**Comment by JAndrassy** [comment]
> Binary was hard to find 

???
it is right there on the release page

**Comment by n1coh** [comment]
I searched for many time the binary before you give me the link.
My message wasn't clear my bad
