### ISSUE TITLE
Download from GitHub releases

### ISSUE THREAD

**Issue by tkbstudios** [JAndrassy/ArduinoOTA#236]
Hello, I would like to download any new release and do an OTA update by downloading from GitHub releases.

But for some reason it doesn't work (I think it's because of HTTPS redirects)

Is there any way to make it work?

https://github.com/tkbstudios/tinet-bridge-esp8266/blob/8b1ccbaddeb60b04542cddbe77f53c2d8d1728e5/tinet-bridge-esp8266.ino#L197

**Comment by JAndrassy** [comment]
you don't use this library. you use the ArduinoOTA library bundled with the esp8266 core
