### ISSUE TITLE
not able to upload the first sketch atmega2560

### ISSUE THREAD

**Issue by golfredom** [jandrassy/ArduinoOTA#25]
trying to upload a example sketch on Arduino Mega 2650,  but i dont undertand the procedure. please help.
![IMG_9619](https://user-images.githubusercontent.com/10067330/81322881-d2b43e80-9051-11ea-87b0-75c0c1a3ae10.jpg)

**Comment by jandrassy** [comment]
select the network port and click the Upload button.
did you copy the platform.local.txt from extras folder next to platform.txt in boards packege folder?
did you burn the Optoboot bootoader to Mega?

**Comment by golfredom** [comment]
Thanks for the reply, yes I did copy the file platform.local.txt

However I don’t know hoy to burn the optoboot boot loader to the mega. Can you explain please. 

Enviado desde mi dispositivo móvil!!!

**Comment by jandrassy** [comment]
https://www.arduino.cc/en/Tutorial/ArduinoISP

**Comment by peros550** [comment]
@jandrassy I need to ask a question. 

I'm trying to change the bootloader to an Arduino Mega 2560. I have prepared an Arduino UNO as an ISP programmer, I have made the correct connections between the two boards (Pogrammer: UNO, Target: Mega2560) 

I am ready to burn the new bootloader as per the instructions [here](https://www.arduino.cc/en/Tutorial/ArduinoISP) and [here ](https://arduino.stackexchange.com/questions/473/how-do-i-burn-the-bootloader)

I have seen in your instructions that you mention: 

"You can download my boards definitions and use it to burn the modified Optiboot and to upload sketches to your Mega over USB and over network."

But I really don't know how to use your "my boards". This part is not clear to me. I think I need to place those files somewhere (probably under C:\Program Files (x86)\Arduino\hardware) , but don't know If I need to replace existing files in Arduino subfolder or put them on a separate folder. 

Could you please clarify?

**Comment by jandrassy** [comment]
look at the picture
https://github.com/jandrassy/my_boards/blob/master/README.MD
