### ISSUE TITLE
ESP8266 and ESP32 not working

### ISSUE THREAD

**Issue by frankygoop** [JAndrassy/ArduinoOTA#259]
Previous versions of ARDUINOOTA worked out of the box. The instructions to use this new version 1.1.0 are very confusing. It is not specified where to replace the platform.txt, etc. for each board is different. 
Can anyone clarify?
thanks

**Comment by JAndrassy** [comment]
maybe you are confusing this library with the ArduinoOTA libraries bundled with the esp8266 and esp32 platform?

**Comment by frankygoop** [comment]
Yes, that could be the reason. However I could not make it work. Even the examples wont compile. I was using the Arduino IDE 1.x and 2.x
