### ISSUE TITLE
Firmware updating doesn't works with huge partition table

### ISSUE THREAD

**Issue by Vano3d** [JAndrassy/ArduinoOTA#261]
Hello,
I'm using huge partition csv:
# Name, Type, SubType, Offset, Size, Flags
nvs, data, nvs, 0x9000, 0x5000,
otadata, data, ota, 0xe000, 0x2000,
app0, app, ota_0, 0x10000, 0x300000,
spiffs, data, spiffs, 0x310000,0xF0000,

ElegantOTA stops updating on 14%, then ESP32 rebooting ((
With standard partition or without updating working perfectly, but I have a big project.

Thanks for assistance!

**Comment by JAndrassy** [comment]
I guess you use the esp32 core's ArduinoOTA library and not this one

**Comment by Vano3d** [comment]
I use much more libs

gyverlibs/GyverOLED@^1.6.1
	gyverlibs/EncButton@^3.6.0
	gyverlibs/GyverTimer@^3.2
	gyverlibs/GyverBlinker@^1.1.0
	bblanchon/ArduinoJson@^7.0.0
	mathieucarbou/AsyncTCP @ 3.2.10
	https://github.com/ayushsharma82/ElegantOTA#3.1.6
	adafruit/Adafruit ADS1X15@^2.5.0
	bodmer/TFT_eSPI@^2.5.43
	gyverlibs/GyverSegment@^1.4.5
build_flags = -DELEGANTOTA_USE_ASYNC_WEBSERVER=1

**Comment by JAndrassy** [comment]
so you use ElegantOTA.  you report the issue in wrong repository

**Comment by Vano3d** [comment]
I used ElegantOTA normally until changed partition.csv
I must look for another cause?

**Comment by JAndrassy** [comment]
why do you ask here? ask there https://github.com/ayushsharma82/ElegantOTA

**Comment by Vano3d** [comment]
OMG, I confused )
