### ISSUE TITLE
Some problems with Arduino R4 Wifi,here is the solution 

### ISSUE THREAD

**Issue by Saettajhones** [JAndrassy/ArduinoOTA#263]
There are some problems on Arduino R4 WiFI. the first thing to do is replace #include <WiFiNINA.h> #include with <WiFiS3.h> . then you need to download the folder https://github.com/arduino/arduinoOTA/releases and copy it into the Arduino directory. On MAC the directory is in Library/Arduino15/Packages/arduino/tools.  We also remind you that when loading the sketch you are asked for a PASSWORD, so type 'password'. This is how everything works. I wasted many hours understanding the problem, I hope it can help someone

**Comment by JAndrassy** [comment]
but there is https://github.com/JAndrassy/ArduinoOTA?tab=readme-ov-file#troubleshooting
