### ISSUE TITLE
ArduinoUNO + Shield : 'InternalStorage' was not declared in this scope

### ISSUE THREAD

**Issue by MrSiO** [jandrassy/ArduinoOTA#27]
Hi.
Have seen this error mentioned in few forum but no resolution.

I'm using an ArduinoUNO with Ethernet shield.
Trying to add ArduinoOTA following the OTEthernet.ino Example as-is but always getting this error while compiling:

'InternalStorage' was not declared in this scope

Using PlatformIO.

Thx for any inputs.

**Comment by jandrassy** [comment]
https://github.com/jandrassy/ArduinoOTA#atmega-support

> The size of networking library and SD library limit the use of ArduinoOTA library to ATmega MCUs with at least 64 kB flash memory.
