### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fragmuffin** [jandrassy/ArduinoOTA#3]
Congratulations on your v1.0 release @jandrassy!

May I make a suggestion to put a `LICENSE` file in the root directory of this repository?
That just makes the software licensing clear.

**Comment by jandrassy** [comment]
thank, you. The repository is based on a copy of Arduino https://github.com/arduino-libraries/WiFi101OTA repository. I didn't notice that it doesn't have a licence file. In source file are licence headers. I add a licence file.

**Comment by fragmuffin** [comment]
Thanks @jandrassy!
