### ISSUE TITLE
Error compiler in   HttpClient http(transport, SERVER, SERVER_PORT);

### ISSUE THREAD

**Issue by franciscogimeno2000** [jandrassy/ArduinoOTA#39]
Hello when compiling with the latest version of ide and your example OTASketchDownload gives an error because
httpclient does not wait for past parameters.

``
  EthernetClient transport;
  HttpClient http(transport, SERVER, SERVER_PORT);  <--------------------------------------error

  char buff[32];
  snprintf(buff, sizeof(buff), PATH, VERSION + 1);

  Serial.print("Check for update file ");
  Serial.println(buff);
``

exit status 1
no matching function for call to 'HttpClient::HttpClient(EthernetClient&, const char*&, const short unsigned int&)'

-----------------------------------------------------------------------------------------------------------------------

I want to update a mega2560 r3 over ethernet.
It is not clear to me if the boot should be changed to optiboot in mega 2560.

Greetings and thanks for your time
Francisco

**Comment by jandrassy** [comment]
install the the ArduinoHttpClient library in Library Manager.

to apply the binary from InternalStorage for AVR, Optiboot with copy_flash_pages function is required
