### ISSUE TITLE
support stm32duino boards 

### ISSUE THREAD

**Issue by jandrassy** [jandrassy/ArduinoOTA#4]
I plan STM32 support, but I have too many Arduino plans. 
All know-how about the flash writing and reading is in the stm32duino EEPROM emulation library.

https://github.com/stm32duino/Arduino_Core_STM32/issues/461

**Comment by jandrassy** [comment]
done for STM32F1

**Comment by gcharles81** [comment]
Hello Any Chance that support will be added to STM32F4XX devices Thanks

**Comment by jandrassy** [comment]
I don't plan to do it, but the F1 support shows how it can be done

**Comment by gcharles81** [comment]
Thanks anyway , its a bit tricky to use the F1 example to port it to the F4 I cannot move forward  because F4 use sectors and not pages that makes writing and reading the flash more complicated.
