### ISSUE TITLE
Add MKR WiFi 1010 to "Boards tested" list

### ISSUE THREAD

**Issue by kpfleming** [jandrassy/ArduinoOTA#46]
I have this working now using InternalStorage. When using SDStorage the upload completed successfully and the Arduino rebooted, but SDU didn't apply the update to the sketch. Since I have plenty of Flash memory space for my sketch, I opted not to try to debug that any further :-)

**Comment by jandrassy** [comment]
https://github.com/arduino/ArduinoCore-samd/issues/563

**Comment by quentin-gilli** [comment]
Hi Fleming, 

Everything works with your MKR? 
I can't get mine to work, while I have no problem with my ESP32.
Are there any differences that can explain this ?

**Comment by jandrassy** [comment]
> Are there any differences that can explain this ?
a completely  different library maybe?

I assume with ESP32 you use the library bundled with the ESP32 boards package, while with MKR you try this library.
What is the problem?
