### ISSUE TITLE
Error whilst uploading sketch

### ISSUE THREAD

**Issue by TykooHagen** [jandrassy/ArduinoOTA#47]
I've got an error whilst trying to upload my sketch to my ESP32-CAM.
I'm using v1.0.5 of the ArduinoOTA and using Arduino IDE.
Following is what shows up on the Serial console

> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:1
> load:0x3fff0018,len:4
> load:0x3fff001c,len:1100
> load:0x40078000,len:9564
> ho 0 tail 12 room 4
> load:0x40080400,len:6320
> entry 0x400806a8
> Booting
> Ready
> IP address: 192.168.0.12
> Start updating sketch
> Progress: 0%
> Progress: 0%
> Progress: 0%
> Progress: 0%
> Progress: 0%
> abort() was called at PC 0x400e2011 on core 1
> 
> Backtrace: 0x4008e8a4:0x3ffb1e30 0x4008ead5:0x3ffb1e50 0x400e2011:0x3ffb1e70 0x40082487:0x3ffb1e90 0x400d4add:0x3ffb1eb0 0x400d4758:0x3ffb1ed0 0x400d4933:0x3ffb1ef0 0x400d4365:0x3ffb1f10 0x400d448e:0x3ffb1f70 0x400d1df2:0x3ffb1f90 0x400d58b1:0x3ffb1fb0 0x4008a849:0x3ffb1fd0
> 
> Rebooting...

Upon decoding it with the EspExceptionDecoder...

> Decoding stack results
> 0x4008e8a4: invoke_abort at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/esp32/panic.c line 155
> 0x4008ead5: abort at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/esp32/panic.c line 170
> 0x400e2011: is_safe_write_address at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/spi_flash/flash_ops.c line 126
> 0x40082487: spi_flash_erase_sector at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/spi_flash/flash_ops.c line 204
> 0x400d4add: EspClass::flashEraseSector(unsigned int) at C:\Users\komfi\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.3\cores\esp32\Esp.cpp line 298
> 0x400d4758: UpdateClass::_writeBuffer() at C:\Users\komfi\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.3\libraries\Update\src\Updater.cpp line 195
> 0x400d4933: UpdateClass::write(unsigned char*, unsigned int) at C:\Users\komfi\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.3\libraries\Update\src\Updater.cpp line 303
> 0x400d4365: ArduinoOTAClass::_runUpdate() at C:\Users\komfi\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.3\libraries\ArduinoOTA\src\ArduinoOTA.cpp line 314
> 0x400d448e: ArduinoOTAClass::handle() at C:\Users\komfi\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.3\libraries\ArduinoOTA\src\ArduinoOTA.cpp line 379
> 0x400d1df2: loop() at C:\Users\komfi\Documents\Arduino\BasicOTA/BasicOTA.ino line 70
> 0x400d58b1: loopTask(void*) at C:\Users\komfi\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.3\cores\esp32\main.cpp line 19
> 0x4008a849: vPortTaskWrapper at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/freertos/port.c line 143

I have no idea what this is about :(

**Comment by jandrassy** [comment]
it is not this library. you use the ArduinoOTA library bundled with the esp32 Arduino boards package
