### ISSUE TITLE
ESP32 OTA update via Ethernet (UIPEthernet)

### ISSUE THREAD

**Issue by frederic-bonjour** [jandrassy/ArduinoOTA#5]
Hi there,

I'd like to know if it's possible to update a sketch on an ESP32 via Ethernet with a ENC28J60 module? I'm using the UIPEthernet library. (Connection to the network is OK and I'm able to send requests over the network via Ethernet.)

The _OTEthernet_ example does not compile, I got the following error:

> 'InternalStorage'` was not declared in this scope

I tried to `#include <InternalStorage.h>`, and the error changes to:

> no matching function for call to 'ArduinoOTAClass::begin(IPAddress, const char [8], const char [9], InternalStorageClass&)'

Any idea?

Thanks! ;)

**Comment by jandrassy** [comment]
esp32 and esp8266 have their own ArduinoOTA library, which uses the core's Updater object. it would be easy to enhance this library for esp8266 and esp32 Arduino core, but it is not done yet

**Comment by frederic-bonjour** [comment]
OK, thank you for your time!

**Comment by jandrassy** [comment]
ESP32 and ESP8266 support added in 1.0.1
