### ISSUE TITLE
Support for SAMD51

### ISSUE THREAD

**Issue by jasonthenderson** [jandrassy/ArduinoOTA#53]
I am trying to add OTA update via wifi download from web to Flash for a SAMD51J20, specifically the Titano (https://learn.adafruit.com/adafruit-pyportal-titano).  Any pointers on how to do this would be appreciated.  

I am pretty basic in my skillset.

**Comment by jandrassy** [comment]
see if you can enhance InternalStorage.cpp

**Comment by jandrassy** [comment]
@jasonthenderson can you please try the SAMD51 support

**Comment by doboszm** [comment]
@jandrassy I just tested it with an adafruit matrixportal using adafruit's wifinina library and a custom board that uses the matrixportal bootloader

**Comment by jandrassy** [comment]
> @jandrassy I just tested it with an adafruit matrixportal using adafruit's wifinina library and a custom board that uses the matrixportal bootloader

MCU. did it work?
btw the bootloader is not important for ARM

**Comment by doboszm** [comment]
> > @jandrassy I just tested it with an adafruit matrixportal using adafruit's wifinina library and a custom board that uses the matrixportal bootloader
> 
> MCU. did it work?
> btw the bootloader used is important only for AVR

ATSAMD51J19A, worked for both serial and network download with a slight modification to both examples (using Adafruit wifinina library instead of Arduino's)
