### ISSUE TITLE
Is support for PlatformIO in your roadmap?

### ISSUE THREAD

**Issue by izamoramx** [jandrassy/ArduinoOTA#54]
First of all I want to thank you guys for your hard work in coming up with a really useful tool for Arduino development. I have been using your library for a few months now and I really love it's simplicity and functionality. 

Unfortunately my projects have become too large to keep developing directly on Arduino IDE and the best solution I have been able to find is PlatformIO which also seems to have some really great features so far. I was very disappointed to see that your library is not available there and also that you recommend not using it. Is there are plans in your roadmap to add support for PlatformIO? I really hope you do, but if you are not planning on it I would appreciate if you could recommend an alternative to your library over there. 

Much appreciated,

Ignacio

**Comment by jandrassy** [comment]
this library relays on Arduino IDE tools for network upload which are not available in Platformio
