### ISSUE TITLE
Arduino Mega 2560 - OTA failed

### ISSUE THREAD

**Issue by peros550** [jandrassy/ArduinoOTA#6]
I tried to push a new firmware using the Arduino GUI on a Arduino Mega 2560 board. I had already flashed a code with your example, therefore I found a new network port on the GUI successfully. 

During the OTA flashing a new window came up asking my password. I gave the correct password but then the password window came up again and again like I had given a wrong password. 

It looks that for me the process cannot complete successfully. 

In the Arduino GUI there was the following error message (in orange)

```
Resetting the board
Failed to reset the board, upload failed
Resetting the board
Failed to reset the board, upload failed
Resetting the board
Failed to reset the board, upload failed

```

**Comment by jandrassy** [comment]
tools.avrdude.upload.network_pattern is not set right. Do you try it with official AVR package? it will not work. Did you change the bootloader? 
https://github.com/jandrassy/ArduinoOTA#atmega-support
I recommend to use ["my_boards"](https://github.com/jandrassy/my_boards) custom hardware configuration to burn the special bootloader and to use the board with it.

**Comment by peros550** [comment]
many thanks for your quick response. 
Is it mandatory to switch bootloader?

**Comment by jandrassy** [comment]
> many thanks for your quick response.
> Is it mandatory to switch bootloader?

yes.

**Comment by peros550** [comment]
I will try it after 2 weeks time and let you know. I will close the issue for now and if I need more help I will get back to you. 
Many thanks for your work,

**Comment by VitorCSoares** [comment]
Hi all, 

What was the solution for this? I think I'm having the exact same problem. I already burn a new bootloader.
Now I'm receiving the following log error message (after introducing the password)

**
C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/arduinoOTA -address 192.168.1.177 -port 65280 -username arduino -password password -sketch C:\Users\Skine\AppData\Local\Temp\arduino_build_137800/OTA_Ethernet_v01_20200421.ino.bin -upload /sketch -b 
flag provided but not defined: -username
Usage of C:\Program Files (x86)\Arduino\hardware\tools\avr\bin\arduinoOTA:
  -address string
    	The address of the board (default "localhost")
  -port string
    	The board needs to be listening on this port (default "80")
  -q	Quiet flag
  -reset string
    	Upload endpoint
  -sketch string
    	Sketch path
  -ssl string
    	SSL flag
  -sync string
    	Upload endpoint
  -sync_exp string
    	sync expected return code in format code:string
  -upload string
    	Upload endpoint
  -v	Verbose flag (default true)
  -version
    	Prints program version
**

**Comment by jandrassy** [comment]
you have old version of ArduinoOTA. I see you have one copied in sketches folder's hardware subbofolder. delete it and/or install a new version of AVR boards package

**Comment by VitorCSoares** [comment]
Hi,

  *   I removed the entire installation.
  *   I installed again everything (v1.8.112);
  *   I added ArduinoOTA from library management screen;

I already tried multiple approaches, so I would like to ask for your help in the next steps. I always have some difficulty with copy the platform.local.txt file step.

Thank you


________________________________
De: Juraj Andrássy <notifications@github.com>
Enviado: 22 de abril de 2020 05:05
Para: jandrassy/ArduinoOTA <ArduinoOTA@noreply.github.com>
Cc: VitorCSoares <Skiner_vitor@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [jandrassy/ArduinoOTA] Arduino Mega 2560 - OTA failed (#6)


you have old version of ArduinoOTA. I see you have one copied in sketches folder's hardware subbofolder. delete it and/or install a new version of AVR boards package

**Comment by jandrassy** [comment]
ok. not very efficient way, but it did install the latest upload tool because it is part of the AVR boards package installed with the IDE. now the AVR boards package is in `C:\Program Files (x86)\Arduino\hardware\arduino\avr` (but if you  update or downgrade the AVR boards package it will be installed in `%userprofile%\AppData\Local\Arduino15\packages\`)

**Comment by VitorCSoares** [comment]
Yes, 
Now I have the installation of the tool again in the C:\Program Files (x86)\Arduino\hardware\arduino\avr.
I already have one Mega 2560 with  Optiboot bootloader.

I copied my_boards to the hardware folder and I can select the board ( Optiboot ) in the IDE. 

I can upload the sketch to my Mega 2560 board through USB but still the same problem when using OTA. 
_Resetting the board
Failed to reset the board, upload failed_

when introducing "password"

**Comment by jandrassy** [comment]
the upload tool sometimes times-out even if the update is sucessful

**Comment by VitorCSoares** [comment]
I got the solution. It was already presented by you multiple times. 
just copy the platform.local.txt to C:\Program Files (x86)\Arduino\hardware\arduino\avr. We will end with platform.txt and platform.local.txt in the same folder. 
Thank you :)

I did not understand your last comment about WiFiOTA.cpp

**Comment by VitorCSoares** [comment]
Hi Jandrassy,

After multiple success tests now I'm having the following problem:

Connecting to board ...  done
Uploading sketch ...  done
Flashing sketch ...  done
Error flashing the sketch:
Error flashing the sketch:

Can you help me please?

**Comment by jandrassy** [comment]
does it update the sketch? did you try to add the status print?

**Comment by VitorCSoares** [comment]
No. The Sketch remains the same. 

Can you give a more detailed explanation of add the status Print? I did not get your point above in the previous message.

**Comment by VitorCSoares** [comment]
I added the Status Code in the WiFiOTA.cpp.
I'm connecting the board via USB to check the Serial Port and I'm doing the update via IP address. 

I'm getting "Unauthorized" as Status. The prompt to insert the password is not appearing now. 

Thank you

**Comment by jandrassy** [comment]
try to set the password in the command in platform.local.txt

**Comment by VitorCSoares** [comment]
Hi, 

It's saying Unauthorized, but the problem seems to be related to the Ethernet Switch I'm using.
If I connect the board (via ethernet) to the same switch my computer is connected I can upload the code.
If I connect the board (via ethernet) to another switch that is connected to the switch my computer is connected I can't see the board Port nether reach it through Program upload.

Maybe one of the switches is blocking some specific port needed. 

Thank you

**Comment by BartArIen** [comment]
HI, 

I have read and followed previous comments: 

1. added [my-boards](https://github.com/jandrassy/my_boards) to Arduino hardware
2. burned the Optiboot to the Arduino Mega 2560
3. copied platform.local.txt to  /Users/bart/Documents/Arduino/hardware/my_boards/avr so I have a platform.local.txt and a platform.txt file in the samen directory. 
4.  changed the password in platform.local.txt to the one in the sketchfile.

But I still get this error 
_Users/bart/Library/Arduino15/packages/arduino/tools/arduinoOTA/1.3.0/bin/arduinoOTA -address 192.168.0.150 -port {upload.network.port} -sketch /var/folders/xm/r4mp8nvn7xd7_mrcm7qfhq2r0000gn/T/arduino_build_187044/sketch_oct27a.ino.hex -upload {upload.network.endpoint_upload} -sync {upload.network.endpoint_sync} -reset {upload.network.endpoint_reset} -sync_exp {upload.network.sync_return} 
Resetting the board
Failed to reset the board, upload failed_

![Screenshot 2020-10-28 at 18 45 26](https://user-images.githubusercontent.com/71131752/97477354-cf8a7300-194f-11eb-9a4e-7aee04cac0ee.png)

Is their a way I can check if the Optiboot loader is burned correctly? What other checks can I do to know what the problem can be?

**Comment by jandrassy** [comment]
platform.local.txt goes to 'official' AVR boards package in IDE installation folder or in Arduino15 folder

**Comment by BartArIen** [comment]
I have moved platform.local.txt to Arduino15, restarted the ide and arduino but still the same error. Any other suggestions i can try?

**Comment by jandrassy** [comment]
> I have moved platform.local.txt to Arduino15, restarted the ide and arduino but still the same error. Any other suggestions i can try?

to Users/bart/Library/Arduino15/packages/arduino/hardware/avr?

**Comment by BartArIen** [comment]
My mistake, in the correct folder as you specified it works, thnx!

**Comment by VitorCSoares** [comment]
Hi @jandrassy. I realized when I do the upload of the code using the programmer I get a success message although the code remains the same. 
Did you faced this behaviour already?

Thank you

**Comment by jandrassy** [comment]
https://github.com/jandrassy/ArduinoOTA#upload-returns-ok-but-the-sketch-is-not-replaced

**Comment by VitorCSoares** [comment]
Does that mean I need to burn a new bootloader again? If I understood correctly this copy_flash_pages function is not present in the bootload I loaded in the past. 
Am I understanding this correctly? 

Sorry for the detailed question.

**Comment by jandrassy** [comment]
sorry, the discussion in this issue is too long to read it again. how do you burn the bootloader?

**Comment by VitorCSoares** [comment]
using your code extracted in May2020

**Comment by jandrassy** [comment]
you meant my_boards. then the bootloader should be OK.
do you use watchdog in your sketch?

**Comment by VitorCSoares** [comment]
no Watchdog. Can you point me how to add it?

**Comment by jandrassy** [comment]
> no Watchdog. Can you point me how to add it?

I asked because it could reset the MCU before copy_flash_pages finished

try to burn the bootloader again. I have no better idea

**Comment by matiasAS** [comment]
Hello @jandrassy

Sorry to ask again for the same. I have copied the platforms.local.txt file to Arduino / hardware / arduino / avr and got this result:
Connecting to board ... done
Uploading sketch ... done
Flashing sketch ... Error flashing the sketch
no protocol:

What I have not done because I understand well how to do it is burn the optiboot bootloader, could you help me please?

Extra information:
Operating system: Linux, Ubuntu 16
Arduino mega

Thank you
I am waiting for you to help me

**Comment by jandrassy** [comment]
do you have the folder structure in sketchbook's hardware folder like this "hardware/my_boards/avr"?

**Comment by matiasAS** [comment]
@jandrassy yes
I from Chile

structure folder:
![image](https://user-images.githubusercontent.com/7276332/122162776-162ad000-ce42-11eb-86ab-f31fa3f9d3d3.png)


list of boards
![image](https://user-images.githubusercontent.com/7276332/122162830-2fcc1780-ce42-11eb-80de-e8f22161ccea.png)

platform.local.txt into Arduino/hardware/arduino/avr:

![image](https://user-images.githubusercontent.com/7276332/122162955-6ace4b00-ce42-11eb-95eb-1cfdcd4a98ae.png)

result upload code:
![image](https://user-images.githubusercontent.com/7276332/122163152-b2ed6d80-ce42-11eb-96af-d03451dab376.png)

regards

**Comment by matiasAS** [comment]
@jandrassy no, sorry

my sketchbook is this:

![image](https://user-images.githubusercontent.com/7276332/122166769-07dfb280-ce48-11eb-90c6-eecddb186a62.png)
regards

**Comment by matiasAS** [comment]
after change sketchbook path as this:

![image](https://user-images.githubusercontent.com/7276332/122168302-1e870900-ce4a-11eb-89d5-e1320f1d4f89.png)

i need copied and install libraries: arduinoota, arduinojson and pubsubclient (mqtt)

results:

![image](https://user-images.githubusercontent.com/7276332/122168192-f5667880-ce49-11eb-94f7-1940feb90753.png)

@jandrassy It is the same original error, I think I am missing an intermediate step which is to burn the bootloader

can you help me with this please?

**Comment by jandrassy** [comment]
your sketchbook folder is /home/Matias/Arduino and this should be in Preferences.
so the location of my_boards folder is right (/home/Matias/Arduino/hardware/my_boards)
do you have avr subfolder in my_boards?

**Comment by matiasAS** [comment]
@jandrassy yes
I have cloned your repository https://github.com/jandrassy/my_boards.git and copied the my_boards folder inside the hardware folder

![image](https://user-images.githubusercontent.com/7276332/122258130-b3b3ed00-ce9e-11eb-8944-26c1be60a749.png)

**Comment by jandrassy** [comment]
what is the libraries folder?

**Comment by matiasAS** [comment]
![image](https://user-images.githubusercontent.com/7276332/122280346-187b4180-ceb7-11eb-8458-52ca3ecb5101.png)

Arduino Mega 2560 (Optiboot) does not appear

**Comment by jandrassy** [comment]
scroll the Tools Board menu down to the end.

**Comment by matiasAS** [comment]
I have checked and nothing that says optiboot. It only appears if I replace the avr folder inside my_boards with the avr in hardware / arduino / avr, but if I do that I lose the programmers, none appear. Also it does not recognize the Arduino.h library


Do you speak Spanish?

**Comment by matiasAS** [comment]
@jandrassy 
after update to 1.8.15:

![image](https://user-images.githubusercontent.com/7276332/122332519-8568f880-cf04-11eb-8cd0-bbd0d25516d7.png)

**Comment by matiasAS** [comment]
@jandrassy I have managed to get the optiboot boards to appear, but when loading the sketch I get the following result

![image](https://user-images.githubusercontent.com/7276332/122333614-6ec3a100-cf06-11eb-99fc-70d322490a35.png)

**Comment by matiasAS** [comment]
There is the possibility that we speak (writing because I do not speak English), by skype, whatsapp, email, more direct so as not to fill out this issue, I have more questions that I would like to ask you

**Comment by jandrassy** [comment]
I don't speak Spanish
you have to burn the bootloader (Optiboot) to be able to upload with Optiboot

**Comment by matiasAS** [comment]
@jandrassy  Can you please tell me how do I burn the bootloader? And another very important thing, can I go back to the original?

**Comment by jandrassy** [comment]
https://www.arduino.cc/en/hacking/bootloader
https://www.arduino.cc/en/Tutorial/BuiltInExamples/ArduinoISP

**Comment by matiasAS** [comment]
@jandrassy I see that the process is not so easy and since I have arduinos in production which is the ones I would like to load the bootloader to, I think it is not convenient for something to fail and run out of arduino. Thank you very much for your help, but I will keep it in mind.

**Comment by matiasAS** [comment]
one more thing, I have an arduino mega that when loading the sketch appears timeout, that is a problem with the bootloader ?, and I have another that the usb port is not recognizable

**Comment by matiasAS** [comment]
@jandrassy I took a risk with a mega arduino that I thought was dead and done, I see that it is not difficult. I give you a challenge: load the sketch binary from the browser in arduino mega like this for esp32: https://lastminuteengineers.com/esp32-ota-web-updater-arduino-ide/amp/

can it be done in e arduino mega?

**Comment by jandrassy** [comment]
> 
> 
> @jandrassy I took a risk with a mega arduino that I thought was dead and done, I see that it is not difficult. I give you a challenge: load the sketch binary from the browser in arduino mega like this for esp32: https://lastminuteengineers.com/esp32-ota-web-updater-arduino-ide/amp/
> 
> can it be done in e arduino mega?

see the Advanced examples. they show how to use InternalStorage to store and apply the update binary.

**Comment by matiasAS** [comment]
@jandrassy When changing the bootloader, is compatibility with any library lost or is everything the same?

**Comment by jandrassy** [comment]
> @jandrassy When changing the bootloader, is compatibility with any library lost or is everything the same?

no other library cares about bootloader. bootloader is only there to write the application to flash memory.

**Comment by matiasAS** [comment]
> > @jandrassy I took a risk with a mega arduino that I thought was dead and done, I see that it is not difficult. I give you a challenge: load the sketch binary from the browser in arduino mega like this for esp32: https://lastminuteengineers.com/esp32-ota-web-updater-arduino-ide/amp/
> > can it be done in e arduino mega?
> 
> see the Advanced examples. they show how to use InternalStorage to store and apply the update binary.

from the browser with the arduino mega I mean this:

![image](https://user-images.githubusercontent.com/7276332/122973767-97f98c80-d35f-11eb-89cf-cefcc480f124.png)

that's in an esp32, can it be done in arduino mega, upload the sketch from a url?

**Comment by matiasAS** [comment]
> > @jandrassy When changing the bootloader, is compatibility with any library lost or is everything the same?
> 
> no other library cares about bootloader. bootloader is only there to write the application to flash memory.

ok, thanks

**Comment by jandrassy** [comment]
> > > @jandrassy I took a risk with a mega arduino that I thought was dead and done, I see that it is not difficult. I give you a challenge: load the sketch binary from the browser in arduino mega like this for esp32: https://lastminuteengineers.com/esp32-ota-web-updater-arduino-ide/amp/
> > > can it be done in e arduino mega?
> > 
> > 
> > see the Advanced examples. they show how to use InternalStorage to store and apply the update binary.
> 
> from the browser with the arduino mega I mean this:
> 
> that's in an esp32, can it be done in arduino mega, upload the sketch from a url?

where do you see a problem?

**Comment by matiasAS** [comment]
My question is because with at least 2 esp32 it has happened to me that when selecting the port (the ip of the esp32) to upload the sketch it does not appear even though it is connected. In order for it to appear again, I must connect it with the usb cable, upload the sketch and there it appears. So that there is that problem, it does not assure me that I can update the sketch if I require it remotely and that is why I think it is much better and safe to do it from a url like the image, because having a connection with the arduino / esp32, if there will be access to upload the sketch binary

do you understand me?

**Comment by matiasAS** [comment]
I want to make a clarification, the esp32 that does not appear to me is connected to a wifi that is created in a raspberry as an access point in a subnet. The ip of the raspberry is 192.168.10.80 and the ip of the esp32 is 192.168.80.10, and that esp32 with the ip 192.168.80.10 does not appear in the list of ports

**Comment by jandrassy** [comment]
https://github.com/jandrassy/ArduinoOTA#ota-upload-from-ide-without-network-port

**Comment by matiasAS** [comment]
hello @jandrassy , I have burned the optiboot bootloader in the arduino mega, loaded my sketch, but the ip of the arduino does not appear in the ports to load the sketch remotely, how do I solve it?

**Comment by matiasAS** [comment]
hello @jandrassy , I have burned the optiboot bootloader in the arduino mega, loaded my sketch and everything fine, what is the difference between ArduinoOTA.poll () and ArduinoOTA.handle ()?

**Comment by jandrassy** [comment]
> hello @jandrassy , I have burned the optiboot bootloader in the arduino mega, loaded my sketch and everything fine, what is the difference between ArduinoOTA.poll () and ArduinoOTA.handle ()?

the WiFi101OTA library which I extended to ArduinoOTA had poll().
ESP ArduinoOTA libraries have handle() so I added it as alias of poll()

**Comment by Trilife** [comment]
Hello @JAndrassy;

So, I'm having some setup related issues, which popped up after I rebuilt my harddrive and reinstalled the Arduino IDE environment. I now have both, V1.8.13 and the newer V2.0.0.0 rc6.

My arduino Mega 2560 has the optiboot loader burnt from before and I already installed your version of the AVR boards in a subdirectory of Documents/Arduino/hardware/my_boards-master  (next to the standard my_boards).

Programming via USB works well.

The Network port shows up as well.

When I try to upload files to the 2560, it asks for a password (I tried leaving it blank, "password" and "myoldpassword") and then I get the following message:
`Resetting the board
Failed to reset the board, upload failed`

Scanning through this thread from the beginning, I see various references to platform.tx and platform.local.txt.

I scanned my disc for these files and they show up in your my_boards-master, as well as in the Program Files (x86) (these seem older though, platform.local being yours, platform being generic).

Now, I vaguely remember having put my username and password in one of these files, but I cannot remember where that file was placed and searching for it in my Gdrive backup of the previous build produces nothing.

So, here are a couple of questions for you, please:

1- in which file do I need to put my username and password in order to secure the upload process?

2- where do I need to place this/these files, in order for the upload to work via Network

3- do we really need to duplicate all these files in Program Files(x86) and in the Document paths?

#3 reminds me of something: during the compile process, I do get a couple of references to duplicate libraries:

`Multiple libraries were found for "Ethernet.h"
 Used: C:\Users\jr\Documents\Arduino\libraries\Ethernet
 Not used: C:\Program Files (x86)\Arduino\libraries\Ethernet
Multiple libraries were found for "SD.h"
 Used: C:\Users\jr\Documents\Arduino\libraries\SD
 Not used: C:\Program Files (x86)\Arduino\libraries\SD
`
no refernce to multiple platform and platform.local though.

Thanks Juray!

**Comment by Trilife** [comment]
> Hello @JAndrassy;
> 
> So, I'm having some setup related issues, which popped up after I rebuilt my harddrive and reinstalled the Arduino IDE environment. I now have both, V1.8.13 and the newer V2.0.0.0 rc6.
> 
> My arduino Mega 2560 has the optiboot loader burnt from before and I already installed your version of the AVR boards in a subdirectory of Documents/Arduino/hardware/my_boards-master (next to the standard my_boards).
> 
> Programming via USB works well.
> 
> The Network port shows up as well.
> 
> When I try to upload files to the 2560, it asks for a password (I tried leaving it blank, "password" and "myoldpassword") and then I get the following message: `Resetting the board Failed to reset the board, upload failed`
> 
> Scanning through this thread from the beginning, I see various references to platform.tx and platform.local.txt.
> 
> I scanned my disc for these files and they show up in your my_boards-master, as well as in the Program Files (x86) (these seem older though, platform.local being yours, platform being generic).
> 
> Now, I vaguely remember having put my username and password in one of these files, but I cannot remember where that file was placed and searching for it in my Gdrive backup of the previous build produces nothing.
> 
> So, here are a couple of questions for you, please:
> 
> 1- in which file do I need to put my username and password in order to secure the upload process?
> 
> 2- where do I need to place this/these files, in order for the upload to work via Network
> 
> 3- do we really need to duplicate all these files in Program Files(x86) and in the Document paths?
> 
> #3 reminds me of something: during the compile process, I do get a couple of references to duplicate libraries:
> 
> `Multiple libraries were found for "Ethernet.h" Used: C:\Users\jr\Documents\Arduino\libraries\Ethernet Not used: C:\Program Files (x86)\Arduino\libraries\Ethernet Multiple libraries were found for "SD.h" Used: C:\Users\jr\Documents\Arduino\libraries\SD Not used: C:\Program Files (x86)\Arduino\libraries\SD ` no refernce to multiple platform and platform.local though.
> 
> Thanks Juray!

Forgot to say that I did copy platform.local.txt from the extras in the library to the my_boards-master/avr/ next to platform.txt

**Comment by JAndrassy** [comment]
https://github.com/JAndrassy/ArduinoOTA#arduinoota-tool-returns-failed-to-reset-the-board-upload-failed

**Comment by Trilife** [comment]
> https://github.com/JAndrassy/Arduino

OTA#arduinoota-tool-returns-failed-to-reset-the-board-upload-failed
> 
> > Forgot to say that I did copy platform.local.txt from the extras in the library to the my_boards-master/avr/ next to platform.txt
> 
> my_boards it is not the right place

Hi Juraj;

Not quite sure what you mean by "my_boards it is not the right place".

I'm guessing you don't mean the my_boards.png file...

I currently have the following setup:
`Documents/Arduino/hardware/my_boards` the /avr subdirectory contains boards, platform.local, platform and programmers.

`Documents/Arduino/hardware/my_boards-master` contains what I downloaded from your github.

I also replaced "arduino" and "password" with my values in both platform and platform.local.  And ArduinoOTA.begin() has the same values.

Do you mean by your comment that I should replace the my_boards folder with the contents of my_boards-master?

Cheers

**Comment by Trilife** [comment]
Follow up:

After I looked closer into the preferences, I ended up placing platform.local into 
Users/me/AppData/Local/Arduino15/packages/arduino/hardware/avr/1.8.5/.

I also had to return the platform and platform.local to remove my custom username/password and return it to arduino/password.

It now is WORKING with Arduino IDE 1.8.13! Thanks for that Juraj.

It still is failing to upload with Arduino IDE 2.0.0. rc6 with the following error:
`Compilation complete.
avrdude: ser_open(): can't open device "192.168.10.249": The system cannot find the file specified.

Upload error: Failed uploading: uploading error: exit status 1
`

Follow-up questions:

1- I see hardware/avr folders in multiple locations: Under Documents/... and AppData/... and Programs(x86)... Is this because of multiple installs 1.8.13 and 2.0.0. rc6?

2- Can I delete some of these, or is it better to do an uninstall and potentially manually remove all things ARDUINO before attempting a new install?

Thanks

**Comment by JAndrassy** [comment]
https://github.com/arduino/arduino-ide/issues/740

1. AVR platform is bundled with IDE 1 installations. it is used until you update it. then it is in then Arduino15 folder
2. the Arduino15 folder is used by all Arduino IDE installations

**Comment by Trilife** [comment]
Thanks Juraj;

I have things working for Arduino 1.8.13 now. It asks me for my password and properly uploads it to the Mega2560 via ethernet. (also via com3/USB)

The Arduino 2.0.0 rc6 is still refusing to upload via Ethernet. But it also refuses to upload via com3/USB).

Ethernet Error message:
`Compilation complete.
"C:\Users\jr\AppData\Local\Arduino15\packages\arduino\tools\arduinoOTA\1.3.0/bin/arduinoOTA" -address 192.168.10.249 -port {upload.port.properties.port} -sketch "C:\Users\jr\AppData\Local\Temp\arduino-sketch-D14456268B98148D7304BC273534F216/A00_Orientes_V21.ino.hex" -upload {upload.port.properties.endpoint_upload} -sync {upload.port.properties.endpoint_sync} -reset {upload.port.properties.endpoint_reset} -sync_exp {upload.port.properties.sync_return}
Resetting the board
Failed to reset the board, upload failed
Upload error: Failed uploading: uploading error: exit status 1
`

USB error Message:
`Compilation complete.
"C:\Users\jr\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17/bin/avrdude" "-CC:\Users\jr\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17/etc/avrdude.conf" -v -V -patmega2560 -cwiring "-PCOM3" -b115200 -D "-Uflash:w:C:\Users\jr\AppData\Local\Temp\arduino-sketch-D14456268B98148D7304BC273534F216/A00_Orientes_V21.ino.hex:i"

avrdude: Version 6.3-20190619
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "C:\Users\jr\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17/etc/avrdude.conf"

         Using Port                    : COM3
         Using Programmer              : wiring
         Overriding Baud Rate          : 115200
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_getsync(): timeout communicating with programmer

avrdude done.  Thank you.

Upload error: Failed uploading: uploading error: exit status 1`

In both cases, I'm using AVR ISP as programmer (same in Arduino 1.8.13, btw).

Any ideas?

Thanks Juraj!

**Comment by JAndrassy** [comment]
why does it upload with avrdude to IP? it is a wrong command. it should use arduinoOTA upload tool.

**Comment by Trilife** [comment]
Hi Juraj;

Looking at the choice of programmers both in 1.8.13 and 2.0.0, I can see two:
 Arduino OTA ( 192.168.1.104) and
Arduino OTA (192.168.10.102)

My LAN is on 192.168.10.XXX, with my desktop used for programming at x.109.

I have no idea from where the IDE got these IP addresses for the Arduino OTA.

Thanks

**Comment by JAndrassy** [comment]
IDE 2 always uses the arduino15 folder for platforms. did you copy platform.local.txt there?

**Comment by JAndrassy** [comment]
IDE 2.0 rc 5 had a different error with OTA upload. I check the rc 6

**Comment by Trilife** [comment]
Ok, Thanks.

In the meantime, I'm thinking of removing both 1.8.13 and 2.0.0 and deleting all references to Arduino from Program Files (x86), Arduino15 and Documents. Then starting from scratch. Does that make sense?

I had the Arduino IDE Windows app installed at one point too. This had caused problems with ArduinoOTA in the beginning. You and I had a ton of back and forths until I finally dumped the Windows app. I'm guessing some of those extra files are a remnant of the App.

**Comment by JAndrassy** [comment]
so the IDE 2 has a different OTA configuration in platform.txt and boards.txt
I made a commit in my_boards https://github.com/JAndrassy/my_boards/commit/259ee6003a4dd7498d6d5c1855fff4f07089d5e2

**Comment by youssiefkhaled** [comment]
> I got the solution. It was already presented by you multiple times. just copy the platform.local.txt to C:\Program Files (x86)\Arduino\hardware\arduino\avr. We will end with platform.txt and platform.local.txt in the same folder. Thank you :)

where is platform.local.txt
