### ISSUE TITLE
Is there any EthernetENC example sketch?

### ISSUE THREAD

**Issue by wieb18** [jandrassy/ArduinoOTA#65]
I am using this ArduinoOTA library with ESP32 and ENC28j60 chip module (EthernetENC library). 

I am just a beginner, my programing knowledge is very limited. My simple approach is using 2 connection (ethernet and wifi). When EthernetENC library detected ethernet cable unplug (LINK OFF) then ESP32 automatically start wifi connection so I could update the sketch using ArduinoOTA over wifi.  

If there is any ArduinoOTA with EthernetENC example for updating the sketch is very helpful for me

**Comment by jandrassy** [comment]
as always, example for Ethernet library applies for EthernetENC library. so OTEthernet example.
but use the GitHub version of the ArduinoOTA library. the released version doesn't support EthernetENC yet.
