### ISSUE TITLE
Arduino MKR Zero with Ethernet Shield not visible

### ISSUE THREAD

**Issue by luke321** [jandrassy/ArduinoOTA#7]
Hello,

I am trying to get my MKR Zero OTA ready, the Ethernet Shield is working I can ping it.

I took the example code and changed it to a static IP.
I cannot see the MKR with a Bonjour Viewer under Windows 10, Bonjour installed with Itunes.
I also used a Network Monitor and could not see any Bonjour related trafic going out from the Arduino.

Do you have any suggestions?

**Comment by jandrassy** [comment]
see here https://github.com/arduino/Arduino/issues/8408

**Comment by luke321** [comment]
Thanks for the fast reply, but I already know that issue thread.
I cannot even see the Arduino in the Bonjour Browser app.

I also tried both Python and Arduino Versions suggested, but since the MKR is not visible in the Bonjour Browser I suspect the culprit elsewhere.

**Comment by jandrassy** [comment]
do the examples of the Ethernet library work?
do you test ArduinoOTA with OTEthernet example?

**Comment by luke321** [comment]
Yes i tested some examples they work, basic http server and also udp sender.
I am currently trying with the OTEthernet example.

**Comment by jandrassy** [comment]
do the examples of the Ethernet library work modified to static IP?

**Comment by luke321** [comment]
Yes they do, this makes it so puzzling for me. I will try another pc tomorrow but I only have Windows 10 available.

**Comment by jandrassy** [comment]
it sometimes help to restart the IDE. 
on my Linux computer the mdns list shows the entry only after the IDE

**Comment by luke321** [comment]
After some windows updates it works now, I actually have to start the IDE first and than start the Arduino while being connected via ethernet. It shows up immediately.

Thanks for the support and this great library!

**Comment by luke321** [comment]
Update:

If anyone encounters similar problems under Windows 10, make sure the network is not set to public, device discovery must be enabled.
And for the discovery to work reliably I had to disable all other network adapters and reboot.
