### ISSUE TITLE
OTA for DUE using esp32

### ISSUE THREAD

**Issue by Murtaza7745** [jandrassy/ArduinoOTA#82]
Hello,
I am a newbie at working with arduino due.
I need help with ota due via esp32.

Please help me ASAP

Awaiting your reply.

**Comment by jandrassy** [comment]
https://github.com/jandrassy/ArduinoOTA/issues/26

**Comment by Murtaza7745** [comment]
I can not understand this, can you explain me some other way or give me some sample code reference for due to perform ota via esp32


> #26

**Comment by jandrassy** [comment]
Due is not supported. In the linked issue they claim to have added support for Due but they didn't cleanup the code to be merged to the library.
