### ISSUE TITLE
Do you have any web server to test OTAskecthDownload ?

### ISSUE THREAD

**Issue by Tindt98** [jandrassy/ArduinoOTA#85]
I tried this example and the returncode is -2

**Comment by jandrassy** [comment]
what do you mean?

**Comment by Tindt98** [comment]
OTAskecthDownload isn't works. i get status code -2

Vào 18:36, Th 5, 20 thg 5, 2021 Juraj Andrássy ***@***.***>
đã viết:

**Comment by jandrassy** [comment]
did you change the example?
error -2 is "This call was made when the HttpClient class wasn't expecting it to be called. Usually indicates your code is using the class incorrectly"

**Comment by Tindt98** [comment]
No, i didn't change anything in your example.

Vào Th 5, 20 thg 5, 2021 vào lúc 20:21 Juraj Andrássy <
***@***.***> đã viết:
