### ISSUE TITLE
That did the trick :)

### ISSUE THREAD

**Issue by alvarooli** [jandrassy/ArduinoOTA#94]
That did the trick :) 

Thanks, I can now upload via OTA.

_Originally posted by @SandraWeddig in https://github.com/jandrassy/ArduinoOTA/issues/10#issuecomment-536578555_

**Comment by alvarooli** [comment]
Hi Sandra! Could you provide detailed information about how did you achieve Ota upload via ethernet? Thank you very much, hope you can help me.

**Comment by jandrassy** [comment]
https://github.com/jandrassy/ArduinoOTA/blob/master/README.md
